### ISSUE TITLE
No way to consume invalid Actions in ChainStates

### ISSUE THREAD

**Issue by 4ever2** [AU-COBRA/ConCert#93]
In the current modelling of blockchains in ConCert there is no way to discard or consume actions in the `chain_state_queue` of a `ChainState` if those actions are invalid.

This is problematic for proofs reasoning about the future state of a blockchain for any ChainState since it is required that the `chain_state_queue` is empty to add new actions and for the blockchain to grow. However it is not possible to prove that the queue can be emptied without the option to discard those actions that cannot be evaluated and thus you can only prove anything about the future of a `ChainState` for ChainStates that have an empty queue.

This does not represent a real blockchain very well since a real blockchain would not get stuck growing just because an invalid transaction or contract call was sent.

**Comment by jakobbotsch** [comment]
The current semantics model the fact that an invalid action rolls back the entire "sub-tree" of actions starting from the originating action, meaning that all of those actions have no effect on the state. This is how it works in Concordium for `and` actions. Allowing actions to be discarded with no change to the state would not model this. But perhaps the model should be expanded to model `or` actions that can be discarded on failure.

> However it is not possible to prove that the queue can be emptied without the option to discard those actions that cannot be evaluated and thus you can only prove anything about the future of a ChainState for ChainStates that have an empty queue.

For our proofs so far we considered blocks that contain some originating actions and either 1. those sub-trees of actions are valid and have some effect on the state, or 2. those sub-trees of actions are invalid and can just be ignored from the perspective of semantics, since they don't affect the state. On 2., the implementation can still grow the blockchain just by ignoring those invalid actions and still model the semantics.

If you are in `ChainState` x and you consider the `ChainState` y as a future, then it is perfectly possible to assume a trace `ChainTrace x y` and then show that something always holds in `y`. [For example, that's done here](https://github.com/AU-COBRA/ConCert/blob/c44e06800e6c4b30ff8bc9ec7536a4a3533ea6e0/execution/examples/BoardroomVoting.v#L467-L519).

Now if you want to show that for instance a smart contract always emits valid actions, then you probably need to do some work, adding some way to assume that actions are valid and express that the contract emits disjoint, valid actions. I'm not sure if allowing discarding actions from the queue would help here, however.

**Comment by annenkov** [comment]
@jakobbotsch If I understand correctly, @4ever2 describes the following scenario. Let's say we've started with a genesis block. We can then apply `step_block`, because `chain_state_queue prev_bstate = []` is satisfied. After we have added a new block, we got some actions in our queue, e.g. transfers of some negative amounts, which is invalid. How do we progress from here? There is no way to apply `step_block` again, since the queue is not empty, and `step_action` doesn't work either, because `eval_transfer` requires `amount >= 0`. I guess we can't, but whether it a problem for the properties we want to show, I don't know.

@4ever2 could you give an example of a property that would require dropping actions?

It might make sense to keep failed top-level actions (from accounts) in the block. Isn't it what happens in the real blockchains?

> On 2., the implementation can still grow the blockchain just by ignoring those invalid actions and still model the semantics.

@jakobbotsch Is my understanding correct that by implementation you mean something external to our model?

**Comment by jakobbotsch** [comment]
Yes, in our semantics it is not valid to add a block with invalid actions. But in reasonable blockchains, such actions do not affect the state (except for gas -- which we don't model). Therefore I don't know if allowing it in the semantics does much. The semantics right now are modelling that there is a way to execute every action in the queue in some order so that you go from the current state to another state.

> @jakobbotsch Is my understanding correct that by implementation you mean something external to our model?

I mean that if you want to write a function that builds a blockchain iteratively by adding blocks, and then prove that your function satisfies the semantics, then you can do that even adding blocks with invalid actions. Then you will be able to show that your implementation implements the semantics for some subset of the actions that are being passed in, i.e. that your implementation finds a subset of valid actions and properly executes those.

**Comment by 4ever2** [comment]
@annenkov An example of a proof is for some `P Q : ChainState -> Prop` prove that `forall prev_bstate, reachable prev_bstate-> P prev_bstate-> exists new_state, reachable new_state /\ Q new_state`, i.e. given some state and a property on that state show that there is a way to get to another state where another property holds. This I can easily prove if i assume `chain_state_queue prev_bstate = []` however that excludes a lot of states for which it should also be provable.

@jakobbotsch I agree that it given how ConCert models actions that comes from contract calls it would not be safe to always allow an action to be discarded. This was also my main concern when I talked with Bas about this. However assuming that queue contains no actions coming from contracts is a lot better than having to assume that the queue is empty.

**Comment by annenkov** [comment]
I talked (separately) with @4ever2 and @jakobbotsch. I'll summarise my understanding below.
Allowing for making progress with actions from users that fail has advantages:

- certain statements about the existence of traces from a given reachable state become more (at least formally) general;
- once we add gas to the model, it makes sense for allowing action from users to fail, since it will actually affect the overall blockchain state due to the cost of gas;
- this assumption (that actions can fail) might be useful for integrating the execution model with "lower" layers, like consensus protocol.

Among the disadvantages, I can only think of the current proofs, which would require fixing.

So, I believe it's would be interesting to carefully extend the current rules to allow such behaviours.

What do you think @4ever2, @jakobbotsch, does that sound right?

**Comment by jakobbotsch** [comment]
Yes, I think it sounds reasonable to do this @annenkov .

**Comment by 4ever2** [comment]
Yes, that sounds right.

**Comment by annenkov** [comment]
Great, since we all agree that it is an interesting extension, @4ever2 feel free to assign yourself to this issue :)

**Comment by 4ever2** [comment]
@annenkov I cannot assign the issue to myself but I am working on it
